export {
  canonicalManifest,
  SOURCE_BASELINE_COMMIT,
} from "./manifest/canonicalManifest";
export type {
  CanonicalEventTitle,
  CanonicalManifest,
  CanonicalSourceFile,
} from "./manifest/types";
export { originalContentRegistry } from "./registry";
export { originalPerks } from "./core/perks";
export {
  originalPrestigeDivisor,
  originalReducedPrestigeStores,
  originalPrestigeStores,
  type OriginalPrestigeStoreType,
} from "./core/prestige";
export {
  ENGINE_GAME_OVER_INITIAL,
  ENGINE_HYPER_MODE_FACTOR,
  ENGINE_INCOME_TICK_MS,
  ENGINE_MAX_STORE,
  ENGINE_SAVE_DISPLAY,
  ENGINE_SITE_URL,
  ENGINE_SITE_URL_ENCODED,
  ENGINE_VERSION,
  STATE_MANAGER_MAX_STORE,
  originalCalculateScore,
  originalEngineOptionDefaults,
  originalScoreBonuses,
  originalScoreFactors,
  originalStateCategories,
  originalStateMigrationSteps,
  type EngineOptionsDefaults,
  type ScoringBonus,
  type StateMigrationStep,
} from "./core/engineData";
export {
  AUDIO_EVENT_DUCK_VOLUME,
  AUDIO_EVENT_FADE_MULTIPLIER,
  AUDIO_FADE_TIME,
  AUDIO_MISSING_BUFFER_CHANNELS,
  AUDIO_MISSING_BUFFER_GAIN_DIVISOR,
  AUDIO_MISSING_BUFFER_SECONDS,
  AUDIO_MISSING_BUFFER_SINE_STEP,
  AUDIO_SAFARI_DECODE_POLL_MS,
  originalAudioManifest,
  type OriginalAudioDefinition,
  type OriginalAudioKind,
} from "./audio/audioManifest";
export {
  LOCALIZATION_BABEL_CONFIG_PATH,
  LOCALIZATION_LANGS_PATH,
  LOCALIZATION_MAIN_CSS_PATH,
  LOCALIZATION_TEMPLATE_MSGID_ENTRIES,
  LOCALIZATION_TEMPLATE_PATH,
  originalDeferredLocalizationScope,
  originalLanguageCodes,
  originalLocaleInventory,
  type OriginalLocaleInventoryEntry,
} from "./localization/localizationManifest";
export {
  EVENT_TIME_RANGE_MINUTES,
  originalExecutionerCombatDefinitions,
  originalEventDefinitions,
  originalSetpieceCombatDefinitions,
  type OriginalCombatDefinition,
  type OriginalCombatSpecialDefinition,
  type OriginalCombatStatus,
  type OriginalEventButtonDefinition,
  type OriginalEventDefinition,
  type OriginalEventSceneDefinition,
} from "./events/eventData";
export {
  DEFAULT_BAG_SPACE,
  DEFAULT_ITEM_WEIGHT,
  PATH_STORES_OFFSET,
  originalPathArmourPriority,
  originalPathBaseCarryables,
  originalPathCapacity,
  originalPathCapacityUpgrades,
  originalPathWeightFor,
  originalPathWeightOverrides,
  type OriginalPathCapacityUpgrade,
  type OriginalPathCarryable,
} from "./path/pathWeights";
export {
  ROOM_BUILDER_INCOME_DELAY,
  ROOM_BUILDER_STATE_DELAY,
  ROOM_BUILDER_WOOD_INCOME,
  ROOM_FIRE_COOL_DELAY,
  ROOM_LIGHT_FIRE_WOOD_COST,
  ROOM_NEED_WOOD_DELAY,
  ROOM_STOKE_COOLDOWN,
  ROOM_STOKE_FIRE_WOOD_COST,
  ROOM_WARM_DELAY,
  originalRoomCost,
  originalRoomCraftables,
  originalRoomFireStates,
  originalRoomMiscItems,
  originalRoomNeedsWorkshop,
  originalRoomTemperatures,
  originalRoomTradeGoods,
  type RoomCostContext,
  type RoomCraftableDefinition,
  type RoomCraftableType,
  type RoomDynamicCost,
  type RoomItemType,
  type RoomMiscItemDefinition,
  type RoomStateDefinition,
  type RoomTradeGoodDefinition,
  type RoomTradeGoodType,
} from "./room/roomData";
export {
  SHIP_ALLOY_PER_HULL,
  SHIP_ALLOY_PER_THRUSTER,
  SHIP_BASE_HULL,
  SHIP_BASE_THRUSTERS,
  SHIP_LIFTOFF_COOLDOWN,
  SPACE_ALTITUDE_TICK_INTERVAL,
  SPACE_ASTEROID_END_TOP,
  SPACE_ASTEROID_SPEED_RANDOM_FACTOR,
  SPACE_BASE_ASTEROID_DELAY,
  SPACE_BASE_ASTEROID_SPEED,
  SPACE_ESCAPE_ALTITUDE,
  SPACE_FADE_TO_BLACK_SPEED,
  SPACE_FRAME_DELAY,
  SPACE_NUM_STARS,
  SPACE_PANEL_SIZE,
  SPACE_SHIP_END_LEFT,
  SPACE_SHIP_END_TOP,
  SPACE_SHIP_EXIT_TOP,
  SPACE_SHIP_MAX_POSITION,
  SPACE_SHIP_MIN_POSITION,
  SPACE_SHIP_SPEED,
  SPACE_SHIP_START_LEFT,
  SPACE_SHIP_START_TOP,
  SPACE_SHIP_TIMER_INTERVAL,
  SPACE_STAR_HEIGHT,
  SPACE_STAR_SPEED,
  SPACE_STAR_WIDTH,
  SPACE_VOLUME_TIMER_INTERVAL,
  originalFabricatorCraftables,
  originalSpaceAsteroidCountForAltitude,
  originalSpaceAsteroidDuration,
  originalSpaceAsteroids,
  originalSpaceAsteroidWaveThresholds,
  originalSpaceBackgroundMusicVolume,
  originalSpaceHitAudioOffset,
  originalSpaceHitAudioTiers,
  originalSpaceKeyBindings,
  originalSpaceNextAsteroidDelay,
  originalSpaceShipSpeed,
  originalSpaceTitleForAltitude,
  originalSpaceTitleThresholds,
  type FabricatorCraftableDefinition,
  type FabricatorCraftableType,
  type SpaceAsteroidDefinition,
  type SpaceAsteroidWaveThreshold,
  type SpaceHitAudioTier,
  type SpaceTitleThreshold,
} from "./lateGame/lateGameData";
export {
  OUTSIDE_CART_GATHER_WOOD_AMOUNT,
  OUTSIDE_GATHER_DELAY,
  OUTSIDE_GATHER_WOOD_AMOUNT,
  OUTSIDE_HUT_ROOM,
  OUTSIDE_POP_DELAY_MAX,
  OUTSIDE_POP_DELAY_MIN,
  OUTSIDE_STORES_OFFSET,
  OUTSIDE_TRAPS_DELAY,
  originalBaitUsedForTraps,
  originalGatherWoodAmount,
  originalMaxPopulation,
  originalOutsideWorkerIncome,
  originalOutsideWorkerUnlocks,
  originalPopulationDelayMinutes,
  originalPopulationIncrease,
  originalPopulationMessageForArrivals,
  originalPopulationMessageThresholds,
  originalTrapDropCount,
  originalTrapDrops,
  originalVillageTitleForHuts,
  originalVillageTitleThresholds,
  type OutsidePopulationMessageThreshold,
  type OutsideTrapDropDefinition,
  type OutsideVillageTitleThreshold,
  type OutsideWorkerIncomeDefinition,
} from "./outside/outsideData";
export {
  WORLD_BASE_HEALTH,
  WORLD_BASE_HIT_CHANCE,
  WORLD_BASE_WATER,
  WORLD_DEATH_COOLDOWN,
  WORLD_DIRECTIONS,
  WORLD_FIGHT_CHANCE,
  WORLD_FIGHT_DELAY,
  WORLD_HYPO_HEAL,
  WORLD_LIGHT_RADIUS,
  WORLD_MEAT_HEAL,
  WORLD_MEDS_HEAL,
  WORLD_MOVES_PER_FOOD,
  WORLD_MOVES_PER_WATER,
  WORLD_RADIUS,
  WORLD_STICKINESS,
  WORLD_TILE,
  WORLD_TILE_PROBS,
  WORLD_VILLAGE_POS,
  originalWorldCompassDirection,
  originalWorldDisplayLabel,
  originalWorldDrawRoad,
  originalWorldGenerateMap,
  originalWorldLightMap,
  originalWorldLandmarks,
  originalWorldMarkVisited,
  originalWorldMapSearch,
  originalWorldNewMask,
  originalWorldWeapons,
  type WorldCompassDirection,
  type WorldLandmarkDefinition,
  type WorldMapGrid,
  type WorldMapSearchResult,
  type WorldMaskGrid,
  type WorldWeaponDefinition,
} from "./world/worldData";
